### ISSUE TITLE
Settings via initialize

### ISSUE THREAD

**Issue by ZebboKlaufix** [errsole/errsole.js#100]
Hi,
is there any plan to set settings like smtp host & port via the initialize object?
And I'd like to set the very first user via cli or the initialize object, too. Is this possible?

Best

**Comment by mrrishimeena** [comment]
@ZebboKlaufix 
We introduced this feature in the web dashboard so users can update settings without redeployment.

**Comment by ZebboKlaufix** [comment]
And this is totally fine. But I'd like to ship an API, where the admin/customer only needs to edit configs in one place. If you would provide smtp ,slack and first-admin in the init object the config could be handled inside one .env file. Currently you need to customize config, start the project AND got the the errsole web-dashboard to create the first-admin and edit smtp & slack.
Or is there any way to configure those options - especially the first-admin - via cli?
