### ISSUE TITLE
Sidebar links without function

### ISSUE THREAD

**Issue by ZebboKlaufix** [errsole/errsole.js#101]
Hi,
if I click on the links in the sidebar nothing happens. If I copy the href into the browsers url bar I can access those pages.
Currently I'm running on Firefox 130.0 and the latest errsole
Links in the top menu bar are functional.

Best

**Comment by mrrishimeena** [comment]
@ZebboKlaufix 
Thanks for reporting this. Working on the issue.

**Comment by mrrishimeena** [comment]
I’ve tested this issue on several browsers, and it appears to be specific to Firefox. While I continue to look for a solution, please use a different browser for now.

**Comment by mrrishimeena** [comment]
@ZebboKlaufix We've released the fix in `errsole v2.10.2`. Please install the latest update. 
Also, be sure to install the upcoming major version of `errsole-sqlite` for the new features.

**Comment by ZebboKlaufix** [comment]
Perfectly working now. Thx!
