### ISSUE TITLE
Feature Request: Customizable setInitializationTimeout for Flexible Initialization Time

### ISSUE THREAD

**Issue by imran-technobotsystem** [errsole/errsole.js#104]
Hello @mrrishimeena,

I hope you're doing well. I’d like to suggest a new feature that allows us to set a custom value for the setInitializationTimeout function during initialization.

Currently, the default timeout is set to 10,000 milliseconds, and we’re encountering the following 
error:
`console.error('Error: Unable to initialize Errsole');`

This error occurs while using a MongoDB connection, and the fixed timeout seems insufficient for certain cases. By allowing us to configure the setInitializationTimeout value, we can adjust it to meet the specific needs of our environment and avoid the timeout issues.

Proposed implementation:

-     Add an option to configure setInitializationTimeout during initialization.
-     Allow custom timeout values to handle various connection conditions.

This feature would help avoid timeout errors, especially in cases where initialization may take longer due to external factors.

We would greatly appreciate your consideration of this feature. 

Thank you!

**Comment by mrrishimeena** [comment]
Hi @imran-technobotsystem , Meanwhile we are working on this issue. You can use a few ways to overcome this problem. 

**Way 1.) You can put errsole.initialize inside a timeout like** 

```
setTimeout(() => {
  errsole.initialize({
    storage: new ErrsoleSQLite('path/to/database.sqlite')
  });
}, waitingtime);

```

**Way 2.) You can use MongoDB connected event and then initialize errsole**

Example Code: 

```
const { MongoClient } = require('mongodb');
const errsole = require('errsole'); // assuming errsole is already installed and required

// Replace with your MongoDB URI
const uri = 'mongodb://localhost:27017';

const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });

client.connect((err) => {
  if (err) {
    console.error('MongoDB connection failed:', err);
  } else {
    console.log('MongoDB connection is ready');
    
    // Initialize Errsole after MongoDB connection is ready
    errsole.initialize({
      storage: new ErrsoleSQLite('path/to/database.sqlite')
    });
    
    console.log('Errsole initialized with SQLite storage.');
    
    const db = client.db('yourDatabaseName');
    // Continue with MongoDB operations
  }
});
```

**Comment by imran-technobotsystem** [comment]
but I am using it as an "expressProxyMiddleware". and I have to put it at
the beginning of all middleware.

like this way

*app.use('/logs', errsole.expressProxyMiddleware());*

so I can't able to use the above solution.

**Comment by imran-technobotsystem** [comment]
Thanks for the great support.

**Comment by mrrishimeena** [comment]
> but I am using it as an "expressProxyMiddleware". and I have to put it at the beginning of all middleware. like this way *app.use('/logs', errsole.expressProxyMiddleware());* so I can't able to use the above solution.

You should be able to use the above solution, even if you are using `app.use('/logs', errsole.expressProxyMiddleware())`

Please give it a try and let me know if you face any issue.
