### ISSUE TITLE
appName parameter is not displayed anywhere on the dashboard

### ISSUE THREAD

**Issue by kush-js** [errsole/errsole.js#115]
When viewing logs on the dashboard, it seems even if there is an appName parameter specified, it does not display anywhere. If using multiple services connected to one errsole database, there is no way to determine or filter what logs came from which service

**Comment by mrrishimeena** [comment]
Errsole currently supports one dashboard per app and environment. For instance, if you’re working on a To-Do app with testing and production environments, you’ll need separate databases—one for testing and one for production.

The `AppName` and `EnvironmentName` settings help you identify which app and environment sent a notification, whether through email or Slack.

In next week’s release, Errsole will allow you to use a single database for multiple apps and environments. However, dashboards will still be separate for each app and environment, meaning you’ll need to access different dashboards for each combination.

**Comment by mrrishimeena** [comment]
I’m happy to inform you that with the latest storage update, we’ve added **tablePrefix/collectionPrefix**. This makes it easier to use one database for multiple apps or environments!
