### ISSUE TITLE
Scam warning

### ISSUE THREAD

**Issue by negezor** [errsole/errsole.js#117]
When I went to check my email today, I found the following email:
<details>
  <summary>Screenshot</summary>
  <img src="https://github.com/user-attachments/assets/f8f07d1e-e9be-495a-9038-cc1692d50eee">
</details>

The link to GitHub and the unsubscribe button leads to a scam resource. Be vigilant if you have received the same email.

<details>
  <summary>Googling domain</summary>
  <img src="https://github.com/user-attachments/assets/b91b5806-06a1-491a-b0fc-589b6fd207eb">
</details>

@venki91 Hi. It might be worth adding a mention in README about possible scam that they want to pull off supposedly from you.

**Comment by mrrishimeena** [comment]
Hi, These are not scam emails. We are reaching out to selected individuals through cold email who have an interest in Node.js. We are using a third-party service called 'Instantly' to send these emails. If the unsubscribe button displays an unrelated link or content, we will address this immediately.

In any case, we do not intend to put anyone in an uncomfortable position. We will fix it right away.
