### ISSUE TITLE
Added Slack URL sanitizer 

### ISSUE THREAD

**Issue by C0oki3s** [errsole/errsole.js#67]
Hey Venki, 

Please check the code which I was forked in my branch because there aren't any branches to create a pull request

**Comment by mrrishimeena** [comment]
Hi, You can create a pull request in the master branch. We will review the changes and then merge them into the master.


Like this: 
<img width="880" alt="Screenshot 2024-05-10 at 12 19 28 AM" src="https://github.com/errsole/errsole.js/assets/1720744/68d2ac60-f536-4ab5-8b11-31f6888cecea">
