### ISSUE TITLE
XSS filter encoding

### ISSUE THREAD

**Issue by C0oki3s** [errsole/errsole.js#74]
Currently any text that been passing from front aren't encoded in the server which will cause XSS and steal Auth Token but its currently is secure and cannot trigger any XSS cause your using antd which will do the work but its better be in prevention mode as antd as 1k+ issues on there github and  it is only recently that they have added XSS filters.

<pre>
exports.filterTxt = (data)=>{
    return data.replace(/[&<>"'`=\/]/g, function(match) {
        switch(match) {
            case '&':
                return '&amp;';
            case '<':
                return '&lt;';
            case '>':
                return '&gt;';
            case '"':
                return '&quot;';
            case "'":
                return '&#39;';
            case '`':
                return '&#x60;';
            case '=':
                return '&#x3D;';
            case '/':
                return '&#x2F;';
            default:
                return match;
        }
    });

}
</pre>

**Comment by C0oki3s** [comment]
I think GitHub is decoding the encoded chars, its weird Lol you can either use URL or HTML encoding

**Comment by venki91** [comment]
@C0oki3s Can you point to the code where XSS is possible? API or function in code.

I think modern browsers prevent XSS attacks with the same-origin policy.

**Comment by C0oki3s** [comment]
No that's wrong you cannot totally trust browser, as your not add any CSP nor using any mitigation to prevent XSS as antd module is providing you protection not sanitation 

<img width="960" alt="image" src="https://github.com/errsole/errsole.js/assets/73307963/2ca9b967-9df2-4e23-be34-30412656ff70">

**Comment by Dev1LRS** [comment]
We are using ReactJS. It has a built-in XSS filter. I have tried to recreate the issue. The script is shown as plain text.
https://www.dhiwise.com/post/react-xss-advanced-strategies-for-mitigating-security-threats

**Comment by venki91** [comment]
We are using ReactJS. It has a built-in XSS filter. I have tried to recreate the issue. The script is shown as plain text.
https://www.dhiwise.com/post/react-xss-advanced-strategies-for-mitigating-security-threats
