### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by Velkamhell97** [errsole/errsole.js#75]
It would be great to use this library with typescript, I hope you can add type definitions soon. Great library 👏

**Comment by mrrishimeena** [comment]
> It would be great to use this library with typescript, I hope you can add type definitions soon. Great library 👏

It works with TypeScript as well. I am sharing a Nest.js TypeScript example as a reference. Please check this to see how you can use it with TypeScript. If you still encounter issues, let us know.

Nest.js example code (with TS): https://github.com/errsole/errsole.js/blob/master/examples/proxy-middleware/nest.ts

TS config example: 
```
import * as errsole from 'errsole';
import * as ErrsoleSequelize from 'errsole-sequelize';

// Insert the Errsole code snippet at the beginning of your app's main file
errsole.initialize({
  storage: new ErrsoleSequelize({
    dialect: 'sqlite',
    storage: '/tmp/logs.sqlite'
  })
});
```

Checkout our documentation: https://github.com/errsole/errsole.js/blob/master/README.md

**Comment by Velkamhell97** [comment]
really ? I will try now, probably I did something wrong. One more question how I can initialize the object without storage I am using express with firebase admin so I want to manually log the errors on my catch blocks. Thanks in advice

**Comment by mrrishimeena** [comment]
> really ? I will try now, probably I did something wrong. One more question how I can initialize the object without storage I am using express with firebase admin so I want to manually log the errors on my catch blocks. Thanks for the fast response

1. To confirm, you are using Express for your application and Firebase for your database, and you want to store your logs in Firebase, correct?

2. Errsole provide custom logging too. For manual logging, you can use either console.error or errsole.error, errsole.warn. In the UI dashboard, you can filter logs to view specific groups of logs you are interested in.
