### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by prestonarnold0** [errsole/errsole.js#79]
![Capture](https://github.com/errsole/errsole.js/assets/169267633/eedd3944-2ec4-4e2e-9369-7c91df5afa30)
![Capture](https://github.com/errsole/errsole.js/assets/169267633/d32bcd91-b2c4-4ed4-9454-00bedfb131d5)

**Comment by SaiKumar2121** [comment]
Hi @prestonarnold0,

Thank you for raising this issue. It looks like the TypeScript compiler is unable to find type declarations for the errsole and errsole-sequelize modules, resulting in the errors you're seeing.

**Solution**
To resolve this issue, you can simply configure your tsconfig.json file to allow implicit any types. Here's how you can do it

**Update tsconfig.json:**
Set "noImplicitAny" to false in your tsconfig.json file. This will allow TypeScript to bypass the missing type declarations for these modules.

![Screenshot from 2024-07-09 11-46-25](https://github.com/errsole/errsole.js/assets/103670141/9c4d6623-e90b-4a0d-9651-363ab3d8c182)
###  Set "noImplicitAny" to false 


![Screenshot from 2024-07-09 11-46-00](https://github.com/errsole/errsole.js/assets/103670141/4d9667fb-383b-4d59-8940-9652a86fd0b5)

**Comment by mrrishimeena** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/169267633/346090766-eedd3944-2ec4-4e2e-9369-7c91df5afa30.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDY4NzksIm5iZiI6MTcyMTEwNjU3OSwicGF0aCI6Ii8xNjkyNjc2MzMvMzQ2MDkwNzY2LWVlZGQzOTQ0LTJlYzQtNGUyZS05MzY5LTdjOTFkZjVhZmEzMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmFkMzIwNGQ2NWRhN2RjMjhmODhjYzZhMzUxNjc3YWQ2MmQ5OGZkMzFlNjk0NGYwNWY5NWEwYjQyMDVhN2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ceyMXGzcCmz9sfBii9tVQjQef8pIDyRmhp46k9zV_VI) ![Capture](https://private-user-images.githubusercontent.com/169267633/346090617-d32bcd91-b2c4-4ed4-9454-00bedfb131d5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDY4NzksIm5iZiI6MTcyMTEwNjU3OSwicGF0aCI6Ii8xNjkyNjc2MzMvMzQ2MDkwNjE3LWQzMmJjZDkxLWIyYzQtNGVkNC05NDU0LTAwYmVkZmIxMzFkNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTJjMTZkZmYzNjM5MGE2MzBhOWUzZTg2MGM4ODdmYzRiMTg5OTI3NjFlZDRhYWVmNmZiNzFlMDljZGUxNTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L6bETXoDE_K3fAPJ1rV8dJerYBoyej0EVYxxFDSSsZA)

We found the issue with the documentation and fixed it. Please go through the updated documentation.
