### ISSUE TITLE
Integrate a date picker into the date input field on the Errsole web dashboard.

### ISSUE THREAD

**Issue by venki91** [errsole/errsole.js#81]
![errsole-datepicker](https://github.com/user-attachments/assets/427c0109-10b8-476a-ac50-756b99389290)

**Comment by Arnab55555** [comment]
I would like to help address this issue. May I work on improving it?

**Comment by venki91** [comment]
@Arnab55555 Sure! Go ahead.

**Comment by Arnab55555** [comment]
Greeting Sir! I have solved the above issue, please check the pull request section

**Comment by mrrishimeena** [comment]
@Arnab55555 Thanks, Let me review it, and then I will merge it.

**Comment by mrrishimeena** [comment]
@SaiKumar2121 The date and time picker has been successfully integrated into the log filters by @Arnab55555 in pull request [#97](https://github.com/errsole/errsole.js/pull/97). Please proceed with the final testing and close the issue once verified.
