### ISSUE TITLE
Avoid returning custom error messages from the API

### ISSUE THREAD

**Issue by venki91** [errsole/errsole.js#82]
Avoid returning custom error messages from the API. Instead, return the error message provided by the storage module, e.g., err.message.

**Comment by venki91** [comment]
Check the files here: https://github.com/errsole/errsole.js/tree/master/lib/main/server/controllers

**Comment by oscarArismendi** [comment]
Hi @venki91,

I'd like to work on the issue you raised about avoiding custom error messages. The solution involves replacing the current custom error messages with `error.message` from the storage module, as per your request.

For example, in the `getSlackDetails` function, I would change:

**Before:**
```javascript
message: 'An unexpected error occurred'
```
**To:**
```javascript
message: error.message
```
This pattern will be applied consistently across all relevant functions in the controllers link that you provide. If you approve, I can start making these changes.

Best regards,
Oscar Arismendi

**Comment by venki91** [comment]
Hi @oscarArismendi ,

Please go a head! Thanks for contributing.
