### ISSUE TITLE
Don't show the "User successfully logged in" modal after a successful login

### ISSUE THREAD

**Issue by venki91** [errsole/errsole.js#83]
![logged-in](https://github.com/user-attachments/assets/808dff31-5fbf-46db-b0c8-d3a0b3ca0250)

**Comment by suhailskhan9** [comment]
I wish to contribute to this project by solving this particular issue. May I try to improve it?

**Comment by Dev1LRS** [comment]
Yes @suhailskhan9, Please do.

**Comment by venki91** [comment]
Yes @suhailskhan9 , please do!

**Comment by venki91** [comment]
@Madhavkumar-04 Yes! Please do.

**Comment by suhailskhan9** [comment]
Yes @venki91 sir, I have started working on it

**Comment by Madhavkumar-04** [comment]
@venki91 Sir I applied for internship in errsole by internshala. I don't get any reply.
I am really interested in doing internship.

**Comment by Madhavkumar-04** [comment]
@venki91 the described error is not visible to me. can you conform it

**Comment by suhailskhan9** [comment]
@venki91 Sir, I am having issues while accessing the web application (especially localhost:8001). Can you suggest me some tips to solve this?

**Comment by mrrishimeena** [comment]
Resolved by @suhailskhan9 , Pull request link: [https://github.com/errsole/errsole.js/pull/93](https://github.com/errsole/errsole.js/pull/93)
