### ISSUE TITLE
After redirecting to the login page, don't show the "Unauthorized" model.

### ISSUE THREAD

**Issue by venki91** [errsole/errsole.js#84]
After redirecting to the login page, don't show the "Unauthorized" model. To reproduce this issue, access the Errsole Web Dashboard at http://localhost:8001/ using an incognito browser window.
![unauthorized](https://github.com/user-attachments/assets/9b2b5f9d-1b40-4730-9c07-2120faca7102)

**Comment by Aditya-Kerkar** [comment]
I wish to contribute to this project. May I take up this issue?

**Comment by Aditya-Kerkar** [comment]
Greetings Sir, I would like to help to solve the above issue by working on this project. May I try to improve it?

**Comment by mrrishimeena** [comment]
@Aditya-Kerkar Sure

**Comment by Aditya-Kerkar** [comment]
Greetings Sir, I have solved the above issue. Please do check the pull request.

**Comment by mrrishimeena** [comment]
Issue has been successfully resolved in [commit](https://github.com/errsole/errsole.js/commit/5810ab2249f5819304e0b95370058c2b2e321f93#diff-4b462ce5b8255b809438fad8b4e34fae4837caee3a7911fdf8723f8e6b2c0f74)
