### ISSUE TITLE
search by meta id?

### ISSUE THREAD

**Issue by restyler** [errsole/errsole.js#86]
I am adding `traceId` field into `.meta()` but searching across web dashboard does not return this row. It would be great to make search work across meta fields. Thanks for a great package!

I also think that "meta" should be rendered in small gray font somewhere when I click on the log entry, as it is too much clicks otherwise to navigate, maybe in serialized+trimmed form in the same line as `Source: errsole   |   Level: error` ?

**Comment by venki91** [comment]
Hi @restyler 

1. Searching within metadata can slow down the app's performance.
2. To improve search efficiency, you can include a traceId in the main log and then search using that traceId. Use the following format:
`errsole.meta(metaJSON).log('Your log message', 'traceId', traceId);`

Let us try a few better options for meta location!
