### ISSUE TITLE
Bug running errsole in mongodb nestjs app

### ISSUE THREAD

**Issue by jerov4ds** [errsole/errsole.js#89]
When I tried to import errsole as you instructed, I added it to my main.ts file as shown

console.log('Initializing Errsole...');
errsole.initialize({
    storage: new ErrsoleMongoDB(process.env.DATABASE_URL, process.env.DATABASE_NAME),
});
console.log('Errsole initialized.');

async function bootstrap() {
       ......
}

I got the error 
errsole.initialize({
        
TypeError: Cannot read properties of undefined (reading 'initialize')
    at Object.<anonymous> (.../src/main.ts:13:9)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    
    
 I had to refactor it to:
 import * as Errsole from 'errsole';

 
 if (Errsole) {
    Errsole.initialize({
        storage: process.env.DATABASE_URL
    });
} else {
    console.error('Failed to initialize errsole: errsole is undefined.');
}

But as you can see, I couldn't use the ErrsoleMongoDB

It will be great if you can provide clarity

**Comment by mrrishimeena** [comment]
Try like this

```
import * as errsole from 'errsole';
import * as ErrsoleMongoDB from 'errsole-mongodb';

import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

errsole.initialize({
  storage: new ErrsoleMongoDB('mongodb-url')
});

async function bootstrap () {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();

```

**Comment by jerov4ds** [comment]
Thanks for the swift response. This worked much better.
