### ISSUE TITLE
Using NestJS ConfigService

### ISSUE THREAD

**Issue by ZebboKlaufix** [errsole/errsole.js#99]
Hi,
I found your very interesting project. and tried to use it in my newest NestJS API.
Is there any chance to use the ConfigService inside of the init options? like:
```
errsole.initialize({
  storage: new ErrsoleSQLite(config.get<string>('LOG_PATH')),
  serverName: 'localhost',
});
```
Thanks

**Comment by mrrishimeena** [comment]
In the code, we're trying to initialize `errsole` before the NestJS application has fully started, but the `ConfigService` isn't available yet. 

To ensure everything works properly in this situation, you can call `errsole.initialize` after the application has fully booted. Although this may result in missing some logs that occur before initialization, placing `errsole.initialize` after the application starts will still allow it to function correctly from that point forward.

**Comment by mrrishimeena** [comment]
Make sure Config get initialized before this code 

```
errsole.initialize({
  storage: new ErrsoleSQLite(config.get<string>('LOG_PATH')),
  serverName: 'localhost',
});
```

**Comment by ZebboKlaufix** [comment]
Works like you said. Thank you.
